name: CI MLflow

on:
  workflow_dispatch:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/main.yml"

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLProject

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip "pip<=25.2"
          pip install mlflow==2.19.0 cloudpickle==3.1.1 numpy==2.3.4 \
                     pandas==2.3.3 pyarrow==18.1.0 scikit-learn==1.7.2 \
                     scipy==1.16.3 matplotlib

      - name: Run MLflow project
        run: |
          mlflow run . --env-manager=local -e train \
            -P test_size=0.2 -P n_estimators=150 -P max_depth=6 \
            -P data_dir=heart_preprocessing

      # (opsional) Upload sebagai artifact juga
      - name: Upload mlruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

      # Commit & push folder mlruns/ ke branch
      - name: Save mlruns to repo
        env:
          GIT_AUTHOR_NAME: ${{ secrets.username }}
          GIT_AUTHOR_EMAIL: ${{ secrets.email }}
          GIT_COMMITTER_NAME: ${{ secrets.username }}
          GIT_COMMITTER_EMAIL: ${{ secrets.email }}
        run: |
          if [ -d "mlruns" ]; then
            git config user.name  "${{ secrets.username }}"
            git config user.email "${{ secrets.email }}"
            git pull --rebase origin master || true
            git add mlruns/
            if ! git diff --staged --quiet; then
              git commit -m "Save mlruns from CI run"
              git push origin HEAD:master
            else
              echo "No changes in mlruns to commit."
            fi
          else
            echo "mlruns folder not found."
          fi
