name: CI MLflow

on:
  workflow_dispatch:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/main.yml"

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLProject

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip "pip<=25.2"
          pip install mlflow==2.19.0 scikit-learn==1.7.2 pandas==2.3.3 numpy==2.3.4 matplotlib

      - name: Run MLflow project (with params)
        env:
          # mlruns disimpan di MLProject/mlruns
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          mlflow run . --env-manager=local -e train \
            -P test_size=0.2 -P n_estimators=150 -P max_depth=6 \
            -P data_dir=heart_preprocessing

      - name: Upload mlruns as artifact
        if: ${{ hashFiles('MLProject/mlruns/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

      # Pastikan secrets terisi (biar gak error "empty ident name")
      - name: Check git identity secrets
        run: |
          if [ -z "${{ secrets.username }}" ] || [ -z "${{ secrets.email }}" ]; then
            echo "ERROR: secrets 'username' dan/atau 'email' belum di-set di repo."
            exit 1
          fi

      - name: Save mlruns to repo
        if: ${{ hashFiles('MLProject/mlruns/**') != '' }}
        env:
          GIT_AUTHOR_NAME: ${{ secrets.username }}
          GIT_AUTHOR_EMAIL: ${{ secrets.email }}
          GIT_COMMITTER_NAME: ${{ secrets.username }}
          GIT_COMMITTER_EMAIL: ${{ secrets.email }}
        run: |
          TARGET_BRANCH="${{ github.ref_name }}"
          git config user.name  "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git pull --rebase origin "$TARGET_BRANCH" || true
          git add mlruns/
          if ! git diff --staged --quiet; then
            git commit -m "Save mlruns from CI run"
            git push origin HEAD:"$TARGET_BRANCH"
          else
            echo "No changes in mlruns to commit."
          fi
